# Generated by Django 2.2.8 on 2023-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=16)),
                ('bday', models.DateField()),
                ('gender', models.BooleanField()),
                ('pwd', models.CharField(max_length=20)),
                ('bookinfo', models.TextField(null=True)),
                ('boardinfo', models.TextField(null=True)),
            ],
        ),
    ]
