# Generated by Django 2.2.8 on 2023-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('bno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=8)),
                ('cno', models.CharField(max_length=8)),
                ('allerinfo', models.CharField(max_length=200, null=True)),
                ('cdate', models.DateField()),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('bno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cno', models.CharField(max_length=8)),
                ('cdate', models.DateField()),
            ],
        ),
    ]
