# Generated by Django 2.2.8 on 2023-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prdlstReportNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('prdlstNm', models.CharField(max_length=200)),
                ('rawmtrl', models.TextField()),
                ('allergy', models.TextField(null=True)),
                ('manufacture', models.CharField(max_length=200, null=True)),
                ('prdkind', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('rnum', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.TextField(null=True)),
                ('older', models.IntegerField(null=True)),
                ('allergy', models.TextField()),
                ('prdlstReportNo', models.CharField(max_length=20)),
                ('prdlstNm', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
