# Generated by Django 4.1.3 on 2022-12-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('rnum', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.TextField()),
                ('older', models.IntegerField()),
                ('allergy', models.TextField()),
                ('prdlstNm', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
