# Generated by Django 4.1.3 on 2022-12-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacture',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='older',
            field=models.IntegerField(null=True),
        ),
    ]
