# Generated by Django 4.1.3 on 2022-12-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_alter_product_allergy_alter_product_manufacture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='rnum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
